### ISSUE TITLE
Axios dependency vulnerability

### ISSUE THREAD

**Issue by luisfonsivevo** [rivet-gg/rivet-node#3]
[package.json](https://github.com/rivet-gg/rivet-node/blob/53936c4cc387a9f9c9bb179cac83a3946ccffd78/package.json#L46) is specifying a [2 year old version of Axios](https://github.com/axios/axios/releases/tag/v0.27.2) that `npm audit fix` isn't able to correct.
https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

```
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/axios
  @rivet-gg/api  *
  Depends on vulnerable versions of axios
  node_modules/@rivet-gg/api

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

**Comment by AngelOnFira** [comment]
Thanks for reaching out about this! We're actually deprecating/archiving this repo in favour of the main repo (https://github.com/rivet-gg/rivet), and we're not using axios there. Thanks for the issue though!
